# Notes


#Sample Dataset Creation

In [ ]:
import csv
import pandas as  pd
import random
import numpy as np

In [ ]:
df = pd.read_csv (r'Israeli Test Data.csv',index_col=False)
print (df)

          test_date  cough  fever  ...  age_60_and_above  gender  test_indication
0        11/03/2021      0      0  ...                No    male            Other
1        11/03/2021      0      0  ...                No  female            Other
2        11/03/2021      0      0  ...                No    male            Other
3        11/03/2021      0      0  ...                No    male           Abroad
4        11/03/2021      0      0  ...                No    male            Other
...             ...    ...    ...  ...               ...     ...              ...
1048570  10/01/2021      0      0  ...               NaN  female            Other
1048571  10/01/2021      0      0  ...                No  female            Other
1048572  10/01/2021      0      0  ...               Yes    male            Other
1048573  10/01/2021      0      0  ...                No    male            Other
1048574  10/01/2021      0      0  ...                No    male            Other

[1048575 rows x

In [ ]:
df = df.loc[ (df['cough']==1)| (df['fever']==1)| (df['sore_throat']==1)| (df['shortness_of_breath']==1)| (df['head_ache']==1)]
df = df.reset_index()
df

index   test_date  ...  gender         test_indication
0           28  11/03/2021  ...    male  Contact with confirmed
1          134  11/03/2021  ...    male  Contact with confirmed
2          266  11/03/2021  ...     NaN  Contact with confirmed
3          373  11/03/2021  ...  female                   Other
4          378  11/03/2021  ...  female                   Other
...        ...         ...  ...     ...                     ...
75765  1048521  10/01/2021  ...    male  Contact with confirmed
75766  1048529  10/01/2021  ...  female                   Other
75767  1048530  10/01/2021  ...  female                   Other
75768  1048534  10/01/2021  ...  female  Contact with confirmed
75769  1048557  10/01/2021  ...  female                   Other

[75770 rows x 11 columns]

In [ ]:
df.sample(frac=1)
df['lc28'] = 0
df['lc56'] = 0
df_mu60 = df.loc[(df['age_60_and_above'] == 'No') & (df['gender'] == 'male')]
df_mo60 = df.loc[(df['age_60_and_above'] == 'Yes') & (df['gender'] == 'male')]
df_fu60 = df.loc[(df['age_60_and_above'] == 'No') & (df['gender'] == 'female')]
df_fo60 = df.loc[(df['age_60_and_above'] == 'Yes') & (df['gender'] == 'female')]

#df_mu60.reset_index()
print(df_mu60['lc28'][0])
for row in df_mu60.iterrows(): #for each row in the file
  n = random.uniform(0, 100) #generate random number
  #print(row[0])
  if n<= 4.094083: #if number below threshold
    df_mu60['lc28'][(row[0])] = 1 #set to lc28
    if n<= 0.367693: #if below lc56 threshold
      df_mu60['lc56'][(row[0])] = 1 #set to lc56
print(df_mu60['lc28'].value_counts())
print(df_mu60['lc56'].value_counts())

for row in df_mo60.iterrows(): #for each row in the file
  n = random.uniform(0, 100) #generate random number
  if n<= 14.38678: #if number below threshold
    df_mo60['lc28'][(row[0])] = 1 #set to lc28
    if n<= 0.730742: #if below lc56 threshold
      df_mo60['lc56'][(row[0])] = 1 #set to lc56
print(df_mo60['lc28'].value_counts())
print(df_mo60['lc56'].value_counts())

for row in df_fu60.iterrows(): #for each row in the file
  n = random.uniform(0, 100) #generate random number
  if n<= 4.632015: #if number below threshold
    df_fu60['lc28'][(row[0])] = 1 #set to lc28
    if n<= 0.378154: #if below lc56 threshold
      df_fu60['lc56'][(row[0])] = 1 #set to lc56

print(df_fu60['lc28'].value_counts())
print(df_fu60['lc56'].value_counts())

for row in df_fo60.iterrows(): #for each row in the file
  n = random.uniform(0, 100) #generate random number
  if n<= 18.6391: #if number below threshold
    df_fo60['lc28'][(row[0])] = 1 #set to lc28
    if n<= 0.906496: #if below lc56 threshold
      df_fo60['lc56'][(row[0])] = 1 #set to lc56
print(df_fo60['lc28'].value_counts())
print(df_fo60['lc56'].value_counts())

dfs = [df_mu60,df_mo60,df_fu60,df_fo60]
df = []
df = pd.concat(dfs)
df


0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


0    28889
1     1319
Name: lc28, dtype: int64
0    30104
1      104
Name: lc56, dtype: int64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


0    2617
1     466
Name: lc28, dtype: int64
0    3070
1      13
Name: lc56, dtype: int64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


0    35473
1     1753
Name: lc28, dtype: int64
0    37072
1      154
Name: lc56, dtype: int64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:43: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:45: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


0    3537
1     812
Name: lc28, dtype: int64
0    4316
1      33
Name: lc56, dtype: int64


index   test_date  cough  ...         test_indication  lc28  lc56
0           28  11/03/2021      1  ...  Contact with confirmed     0     0
1          134  11/03/2021      0  ...  Contact with confirmed     0     0
7          436  11/03/2021      0  ...                   Other     0     0
8          445  11/03/2021      0  ...                   Other     0     0
13         839  11/03/2021      1  ...                   Other     0     0
...        ...         ...    ...  ...                     ...   ...   ...
75727  1048000  10/01/2021      1  ...  Contact with confirmed     0     0
75749  1048341  10/01/2021      1  ...                   Other     0     0
75760  1048487  10/01/2021      1  ...                   Other     1     0
75766  1048529  10/01/2021      0  ...                   Other     0     0
75768  1048534  10/01/2021      0  ...  Contact with confirmed     0     0

[74866 rows x 13 columns]

In [ ]:
df.to_csv('sample.csv', encoding='utf-8')

In [ ]:
df['asthma'] = 0
for row in df.iterrows(): #for each row in the file
  n = random.uniform(0, 100) #generate random number
  if df['lc56'][(row[0])] == 1:
    if n<= 18.0:
      df['asthma'][(row[0])] = 1
  elif df['lc28'][(row[0])] == 1:
    if n<= 15.8:
      df['asthma'][(row[0])] = 1
  else:
    if n<= 7.7:
      df['asthma'][(row[0])] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


#None Federated Learning

In [ ]:
import csv
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv (r'Sample Dataset.csv',index_col=False)
print (df)

       cough  fever  sore_throat  ...  lc28  lc56 asthma
0          1      0            0  ...     0     0      0
1          0      0            0  ...     0     0      0
2          0      0            1  ...     0     0      0
3          0      0            1  ...     0     0      0
4          1      1            0  ...     0     0      0
...      ...    ...          ...  ...   ...   ...    ...
74861      1      1            1  ...     0     0      0
74862      1      1            0  ...     0     0      0
74863      1      0            1  ...     1     0      0
74864      0      0            1  ...     0     0      0
74865      0      0            1  ...     0     0      0

[74866 rows x 10 columns]


In [ ]:
df.columns
df = df.dropna()
df

cough  fever  sore_throat  ...  lc28  lc56 asthma
0          1      0            0  ...     0     0      0
1          0      0            0  ...     0     0      0
2          0      0            1  ...     0     0      0
3          0      0            1  ...     0     0      0
4          1      1            0  ...     0     0      0
...      ...    ...          ...  ...   ...   ...    ...
74861      1      1            1  ...     0     0      0
74862      1      1            0  ...     0     0      0
74863      1      0            1  ...     1     0      0
74864      0      0            1  ...     0     0      0
74865      0      0            1  ...     0     0      0

[74866 rows x 10 columns]

In [ ]:
df['label'] = 0
df['label'] = np.where((df['lc28'] == 1) | (df['lc56'] == 1), 1,0)
del df['lc28']
del df['lc56']
df

cough  fever  sore_throat  ...  gender  asthma label
0          1      0            0  ...    male       0     0
1          0      0            0  ...    male       0     0
2          0      0            1  ...    male       0     0
3          0      0            1  ...    male       0     0
4          1      1            0  ...    male       0     0
...      ...    ...          ...  ...     ...     ...   ...
74861      1      1            1  ...  female       0     0
74862      1      1            0  ...  female       0     0
74863      1      0            1  ...  female       0     1
74864      0      0            1  ...  female       0     0
74865      0      0            1  ...  female       0     0

[74866 rows x 9 columns]

In [ ]:
df['gender'] = np.where((df['gender'] == 'male'), 1,0)
df['age_60_and_above'] = np.where((df['age_60_and_above'] == 'Yes'), 1,0)
df

cough  fever  sore_throat  ...  gender  asthma  label
0          1      0            0  ...       0       0      0
1          0      0            0  ...       0       0      0
2          0      0            1  ...       0       0      0
3          0      0            1  ...       0       0      0
4          1      1            0  ...       0       0      0
...      ...    ...          ...  ...     ...     ...    ...
74861      1      1            1  ...       0       0      0
74862      1      1            0  ...       0       0      0
74863      1      0            1  ...       0       0      1
74864      0      0            1  ...       0       0      0
74865      0      0            1  ...       0       0      0

[74866 rows x 9 columns]

In [ ]:
df_positive = df[df.label == 1]
df_negative = df[df.label ==0]
df_negative = df_negative.sample(n=(len(df_positive)))
print(len(df_positive))
print(len(df_negative))
dfs = [df_positive,df_negative]
df_balanced = pd.concat(dfs)
del df_positive
del df_negative
df_balanced.sample(frac=1)
df_balanced


4350
4350


cough  fever  sore_throat  ...  gender  asthma  label
59         1      1            0  ...       0       0      1
66         1      1            0  ...       0       0      1
71         1      0            1  ...       0       0      1
134        0      0            1  ...       0       0      1
190        0      0            1  ...       0       0      1
...      ...    ...          ...  ...     ...     ...    ...
65635      1      0            1  ...       0       0      0
33908      1      1            1  ...       0       0      0
67012      1      0            1  ...       0       0      0
1975       1      0            0  ...       0       0      0
13026      1      1            0  ...       0       0      0

[8700 rows x 9 columns]

In [ ]:
df_balanced.sample(frac=1)
df.to_csv('SampleDataPP.csv', index=False,header=False)

In [ ]:
df_balanced.sample(frac=1)
from sklearn.model_selection import train_test_split

y = df_balanced.loc[:,'label'].values
del df_balanced['label']
y



array([ 1,  1,  1, ..., -1, -1, -1])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df_balanced, y, test_size = 0.2)
print(x_train)
print(x_test)
print(len(y_train))
print(len(y_test))

       cough  fever  sore_throat  ...  age_60_and_above  gender  asthma
73092      0      0            0  ...                 1      -1       0
37318      0      0            1  ...                -1      -1       0
40789      0      0            0  ...                -1      -1       0
12476      0      1            0  ...                -1       1       0
37952      1      0            0  ...                -1      -1       0
...      ...    ...          ...  ...               ...     ...     ...
50185      1      0            0  ...                -1      -1       0
13809      1      0            0  ...                -1       1       0
60922      1      0            0  ...                -1      -1       0
30962      1      0            0  ...                 1       1       0
59826      0      0            0  ...                -1      -1       0

[6744 rows x 9 columns]
       cough  fever  sore_throat  ...  age_60_and_above  gender  asthma
48067      0      0            0  ...  

## SVM Model

In [ ]:
from sklearn import svm
clf = svm.SVC()
clf.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score
pred_values = clf.predict(x_test)

print(confusion_matrix(y_test, pred_values))
print('Accuracy: ',accuracy_score(y_test, pred_values))
print('precision: ', precision_score(y_test, pred_values))
print('Recall: ',recall_score(y_test, pred_values))

[[708 139]
 [468 371]]
Accuracy:  0.6399762752075919
precision:  0.7274509803921568
Recall:  0.44219308700834326


##KNN Model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=11)
neigh.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [ ]:
pred_values = neigh.predict(x_test)

print(confusion_matrix(y_test, pred_values))
print('Accuracy: ',accuracy_score(y_test, pred_values))
print('precision: ', precision_score(y_test, pred_values))
print('Recall: ',recall_score(y_test, pred_values))

[[547 300]
 [359 480]]
Accuracy:  0.6091340450771056
precision:  0.6153846153846154
Recall:  0.5721096543504172


##Decision Tree Classifier

In [ ]:
from sklearn import tree
clf_tree = tree.DecisionTreeClassifier()
clf_tree = clf.fit(x_train,y_train)

In [ ]:
pred_values = clf_tree.predict(x_test)

print(confusion_matrix(y_test, pred_values))
print('Accuracy: ',accuracy_score(y_test, pred_values))
print('precision: ', precision_score(y_test, pred_values))
print('Recall: ',recall_score(y_test, pred_values))

[[708 139]
 [468 371]]
Accuracy:  0.6399762752075919
precision:  0.7274509803921568
Recall:  0.44219308700834326


##Neural Network

In [ ]:
from sklearn.neural_network import MLPClassifier
nn_clf = MLPClassifier(random_state=1)
nn_clf.fit(x_train,y_train)

In [ ]:
pred_values = nn_clf.predict(x_test)

print(confusion_matrix(y_test, pred_values))
print('Accuracy: ',accuracy_score(y_test, pred_values))
print('precision: ', precision_score(y_test, pred_values))
print('Recall: ',recall_score(y_test, pred_values))

[[696 151]
 [471 368]]
Accuracy:  0.631079478054567
precision:  0.7090558766859345
Recall:  0.43861740166865315


##Keras Learning

In [ ]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
from numpy import loadtxt

In [ ]:
import csv
import pandas as pd
import numpy as np

df = pd.read_csv (r'Sample Dataset.csv',index_col=False)
df = df.dropna()
df['label'] = 0
df['label'] = np.where((df['lc28'] == 1) | (df['lc56'] == 1), 1,0)
del df['lc28']
del df['lc56']
df['gender'] = np.where((df['gender'] == 'male'), 1,0)
df['age_60_and_above'] = np.where((df['age_60_and_above'] == 'Yes'), 1,0)
df_positive = df[df.label == 1]
df_negative = df[df.label ==0]
df_negative = df_negative.sample(n=(len(df_positive)))
print(len(df_positive))
print(len(df_negative))
dfs = [df_positive,df_negative]
df_balanced = pd.concat(dfs)
del df_positive
del df_negative
df_balanced = df_balanced.sample(frac=1)
df_balanced

4350
4350


cough  fever  sore_throat  ...  gender  asthma  label
5590       0      1            0  ...       1       0      1
50031      0      0            1  ...       0       0      1
66502      0      0            0  ...       0       0      0
63336      1      0            0  ...       0       0      1
50563      1      0            0  ...       0       0      0
...      ...    ...          ...  ...     ...     ...    ...
60222      1      0            0  ...       0       0      1
73285      1      1            0  ...       0       0      1
37633      1      1            0  ...       0       0      0
6580       0      0            0  ...       1       0      0
72962      0      0            0  ...       0       0      1

[8700 rows x 9 columns]

In [ ]:
msk = np.random.rand(len(df_balanced)) < 0.9

df_test = df_balanced[~msk]
df_balanced = df_balanced[msk]

print(len(df_balanced))
print(len(df_test))

7818
882


In [ ]:
x_test = df_test.values[:,0:8]
y_test = df_test.values[:,8]
x_train = df_balanced.values[:,0:8]
y_train = df_balanced.values[:,8]
print(len(x_test))
print(len(y_test))
print(len(x_train))
print(len(y_train))

882
882
7818
7818


In [ ]:
df_balanced.dtypes

cough                  int64
fever                  int64
sore_throat            int64
shortness_of_breath    int64
head_ache              int64
age_60_and_above       int64
gender                 int64
asthma                 int64
label                  int64
dtype: object

In [ ]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=200, batch_size=100)

Epoch 1/200
79/79 [==============================] - 1s 1ms/step - loss: 0.7136 - accuracy: 0.4978
Epoch 2/200
79/79 [==============================] - 0s 1ms/step - loss: 0.6822 - accuracy: 0.5331
Epoch 3/200
79/79 [==============================] - 0s 1ms/step - loss: 0.6656 - accuracy: 0.5996
Epoch 4/200
79/79 [==============================] - 0s 1ms/step - loss: 0.6552 - accuracy: 0.6189
Epoch 5/200
79/79 [==============================] - 0s 1ms/step - loss: 0.6440 - accuracy: 0.6372
Epoch 6/200
79/79 [==============================] - 0s 1ms/step - loss: 0.6451 - accuracy: 0.6320
Epoch 7/200
79/79 [==============================] - 0s 1ms/step - loss: 0.6465 - accuracy: 0.6297
Epoch 8/200
79/79 [==============================] - 0s 1ms/step - loss: 0.6495 - accuracy: 0.6250
Epoch 9/200
79/79 [==============================] - 0s 1ms/step - loss: 0.6428 - accuracy: 0.6363
Epoch 10/200
79/79 [==============================] - 0s 1ms/step - loss: 0.6509 - accuracy: 0.6283
Epoch 11/

In [ ]:
import os
save_path = r"model"

In [ ]:
model.save_weights("covid_model-weights.h5")
model_json = model.to_json()
with open("covid_model.json","w") as json_file:
  json_file.write(model_json)

In [ ]:
# evaluate the keras model
_, accuracy = model.evaluate(x_test, y_test)
print('Accuracy: %.2f' % (accuracy*100))

27/27 [==============================] - 0s 1ms/step - loss: 0.8225 - accuracy: 0.6099
Accuracy: 60.99


In [ ]:
model.save("longCovidPrediction")

INFO:tensorflow:Assets written to: longCovidPrediction/assets


In [ ]:
!zip -r /content/longCovidPrediction.zip /content/longCovidPrediction/
from google.colab import files
files.download('longCovidPrediction.zip') 

  adding: content/longCovidPrediction/ (stored 0%)
  adding: content/longCovidPrediction/saved_model.pb (deflated 88%)
  adding: content/longCovidPrediction/variables/ (stored 0%)
  adding: content/longCovidPrediction/variables/variables.index (deflated 63%)
  adding: content/longCovidPrediction/variables/variables.data-00000-of-00001 (deflated 50%)
  adding: content/longCovidPrediction/assets/ (stored 0%)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
def federateData(data, numClients):
    avg = len(data) / float(numClients)
    out = []
    last = 0.0
    while last < len(data):
        out.append(data[int(last):int(last + avg)])
        last += avg
    for i in range(len(out)):
      out[i] = np.asarray(out[i]).astype(np.float32)
      if i == 0:
        tensor_out = tf.convert_to_tensor(out[i])
        print(i)
        print('Tensor Out')
        print(tensor_out)
      else:
        print(i)
        print('Tensor Out')
        print(tensor_out)
        print('New Tensor')
        print(tf.convert_to_tensor(out[i]))
        tensor_out = tf.concat([tensor_out,tf.convert_to_tensor(out[i])],1)
    return tensor_out

x = (federateData(x_test,NUM_CLIENTS))

#x_test_fed = np.array(federateData(x_test,NUM_CLIENTS))
#x_train_fed = np.array(federateData(x_train,NUM_CLIENTS))
#y_train_fed = np.array(federateData(y_train,NUM_CLIENTS))
#y_test_fed = np.array(federateData(y_test,NUM_CLIENTS))

for i in range(len(x_test_fed)):
  print(x_test_fed[i].shape)

0
Tensor Out
tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 ...
 [0. 0. 1. ... 0. 1. 1.]
 [1. 1. 0. ... 0. 1. 0.]
 [1. 1. 0. ... 1. 0. 0.]], shape=(1871, 8), dtype=float32)
1
Tensor Out
tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 ...
 [0. 0. 1. ... 0. 1. 1.]
 [1. 1. 0. ... 0. 1. 0.]
 [1. 1. 0. ... 1. 0. 0.]], shape=(1871, 8), dtype=float32)
New Tensor
tf.Tensor(
[[1. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 ...
 [1. 0. 1. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 1. 0. 0.]], shape=(1872, 8), dtype=float32)


InvalidArgumentError: ignored

In [ ]:
x_test_fed = np.asarray(x_test_fed).astype('float32')
tensor = tf.convert_to_tensor(x_test_fed)

ValueError: ignored

In [ ]:
def create_keras_model():
  return tf.keras.models.Sequential([
      tf.keras.layers.Input(shape=(8,)),
      tf.keras.layers.Dense(8,activation='relu'),
      tf.keras.layers.Dense(1,activation='sigmoid'),
  ])
def model_fn():
  keras_model = create_keras_model()
  return tff.learning.from_keras_model(
      keras_model,
      input_spec = tf.nest.map_structure(tf.TensorSpec.from_tensor,
                  [train,test]),
      loss=tf.keras.losses.SparseCategoricalCrossentropy(),
      metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])
print(model_fn())

'''
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
'''

ValueError: ignored

In [ ]:
print(tf.nest.map_structure(lambda x: tf.TensorSpec(x.shape, x.dtype), x_train_fed[0]))

TensorSpec(shape=(5614, 8), dtype=tf.float64, name=None)


#FedLearning Attempt


In [ ]:
import numpy as np
from numpy import loadtxt
dataset = loadtxt(r'SampleDataPP.csv', delimiter=',')
dataset

array([[1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [1., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [ ]:
!pip install --quiet --upgrade tf.data
!pip install --quiet --upgrade tfds
!pip install --quiet --upgrade tensorflow_federated
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_federated as tff

     |████████████████████████████████| 3.8MB 7.4MB/s 
     |████████████████████████████████| 2.9MB 44.6MB/s 
ERROR: tf-nightly 2.6.0.dev20210402 has requirement gast==0.4.0, but you'll have gast 0.3.3 which is incompatible.
ERROR: tf-nightly 2.6.0.dev20210402 has requirement grpcio~=1.34.0, but you'll have grpcio 1.32.0 which is incompatible.
ERROR: tf-nightly 2.6.0.dev20210402 has requirement h5py~=3.1.0, but you'll have h5py 2.10.0 which is incompatible.
ERROR: tensorflow-federated-nightly 0.18.0.dev20210403 has requirement grpcio~=1.34.0, but you'll have grpcio 1.32.0 which is incompatible.
ERROR: Could not find a version that satisfies the requirement tfds (from versions: none)
ERROR: No matching distribution found for tfds


In [ ]:

x = dataset[:,0:8]
y = dataset[:,8]


x_tensor = tf.convert_to_tensor(x, dtype=tf.float32)
y_tensor  = tf.convert_to_tensor(y, dtype=tf.float32)


In [ ]:
train_number = int(x_tensor.shape[0]/100*80)
x_train_tensor = x_tensor[train_number:]
y_train_tensor = y_tensor[train_number:]
x_test_tensor = x_tensor[:train_number]
y_test_tensor = y_tensor[:train_number]
print('Tensor Lengths: ')
print('x_train: ',x_train_tensor)
print('y_train: ',y_train_tensor)
print('x_test: ',x_test_tensor)
print('y_test: ',y_test_tensor)


#dataset = tf.data.Dataset.from_tensor_slices((x_train_tensor, y_train_tensor))
print(dataset)

Tensor Lengths: 
x_train:  tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]], shape=(14974, 8), dtype=float32)
y_train:  tf.Tensor([0. 0. 0. ... 1. 0. 0.], shape=(14974,), dtype=float32)
x_test:  tf.Tensor(
[[1. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(59892, 8), dtype=float32)
y_test:  tf.Tensor([0. 0. 0. ... 0. 0. 0.], shape=(59892,), dtype=float32)
[[1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 1. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [ ]:
import csv
import pandas as pd
import numpy as np

df = pd.read_csv (r'Sample Dataset.csv',index_col=False)
df = df.dropna()
df['label'] = 0
df['label'] = np.where((df['lc28'] == 1) | (df['lc56'] == 1), 1,0)
del df['lc28']
del df['lc56']
df['gender'] = np.where((df['gender'] == 'male'), 1,0)
df['age_60_and_above'] = np.where((df['age_60_and_above'] == 'Yes'), 1,0)
df_positive = df[df.label == 1]
df_negative = df[df.label ==0]
df_negative = df_negative.sample(n=(len(df_positive)))
print(len(df_positive))
print(len(df_negative))
dfs = [df_positive,df_negative]
df_balanced = pd.concat(dfs)
del df_positive
del df_negative
df_balanced.sample(frac=1)
df_balanced


4350
4350


cough  fever  sore_throat  ...  gender  asthma  label
59         1      1            0  ...       1       0      1
66         1      1            0  ...       1       0      1
71         1      0            1  ...       1       0      1
134        0      0            1  ...       1       0      1
190        0      0            1  ...       1       0      1
...      ...    ...          ...  ...     ...     ...    ...
69024      0      0            1  ...       0       0      0
25020      1      0            0  ...       1       0      0
22811      0      1            0  ...       1       0      0
48195      1      1            0  ...       0       0      0
410        0      1            0  ...       1       0      0

[8700 rows x 9 columns]

In [ ]:
train_number = int(len(df_balanced)/100*80)
df_train = df_balanced[:train_number]
df_test = df_balanced[train_number:]
print(len(df_train),' / ',len(df_test))
df_train

6960  /  1740


cough  fever  sore_throat  ...  gender  asthma  label
59         1      1            0  ...       1       0      1
66         1      1            0  ...       1       0      1
71         1      0            1  ...       1       0      1
134        0      0            1  ...       1       0      1
190        0      0            1  ...       1       0      1
...      ...    ...          ...  ...     ...     ...    ...
10000      1      1            0  ...       1       0      0
50630      0      1            1  ...       0       0      0
1475       1      0            0  ...       1       0      0
66598      1      0            0  ...       0       1      0
35022      1      0            1  ...       0       0      0

[6960 rows x 9 columns]

In [ ]:
def dfToTensor(df):
  label = df.pop('label')
  dataset = tf.data.Dataset.from_tensor_slices((df.values, label.values))
  return dataset

In [ ]:
tfTrain = dfToTensor(df_train)
tfTest = dfToTensor(df_test)

#dataset = tf.data.Dataset.from_tensor_slices((df_balanced.values, label.values))

In [ ]:
tfTrain.element_spec[0].shape

TensorShape([8])

In [ ]:
for i in range(1, NUM_CLIENTS+1):
    client_ids.append("client_" + str(i))

def create_tf_dataset_for_client_fn(client_id,size):
  # a function which takes a client_id and returns a
  # tf.data.Dataset for that client
  client_data = df_train[start:end]
  client_data = df[df[client_id_colname] == client_id]
  dataset = tf.data.Dataset.from_tensor_slices(client_data.to_dict('list'))
  dataset = dataset.shuffle(SHUFFLE_BUFFER).batch(1).repeat(NUM_EPOCHS)
  return dataset

NameError: ignored

In [ ]:
y = df_train.loc[:,'label'].values
del df_train['label']

In [ ]:
import collections
client_train_dataset = collections.OrderedDict()
rows_per_set = 6960
client_ids = []
for i in range(1, NUM_CLIENTS+1):
    client_name = "client_" + str(i)
    client_ids.append(client_name)
    start = rows_per_set * (i-1)
    end = rows_per_set * i
    print(client_name,start,end)
    print(f"Adding data from {start} to {end} for client : {client_name}")
    data = collections.OrderedDict((('label', y[start:end]), ('data', df_train[start:end])))
    client_train_dataset[client_name] = data
train_dataset = tff.simulation.FromTensorSlicesClientData(client_train_dataset)
print(client_ids)
print(train_dataset)

client_1 0 6960
Adding data from 0 to 6960 for client : client_1


NameError: ignored

In [ ]:
train_dataset

##Data Preprocessing

In [ ]:
#@test {"skip": true}

# tensorflow_federated_nightly also bring in tf_nightly, which
# can causes a duplicate tensorboard install, leading to errors.
!pip uninstall --yes tensorboard tb-nightly
!pip install --quiet --upgrade tensorflow_federated
!pip install --quiet --upgrade tensorflow-federated-nightly
!pip install --quiet --upgrade nest-asyncio
!pip install --quiet --upgrade tb-nightly  # or tensorboard, but not both
import nest_asyncio
nest_asyncio.apply()

Uninstalling tensorboard-2.4.1:
  Successfully uninstalled tensorboard-2.4.1
     |████████████████████████████████| 583kB 12.7MB/s 
     |████████████████████████████████| 194kB 15.2MB/s 
     |████████████████████████████████| 174kB 32.5MB/s 
     |████████████████████████████████| 706kB 31.8MB/s 
     |████████████████████████████████| 6.0MB 66.8MB/s 
     |████████████████████████████████| 3.9MB 76.8MB/s 
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
     |████████████████████████████████| 604kB 13.7MB/s 
     |████████████████████████████████| 456.7MB 44kB/s 
     |████████████████████████████████| 51kB 5.3MB/s 
     |████████████████████████████████| 4.0MB 63.4MB/s 
     |████████████████████████████████| 5.9MB 58.4MB/s 
     |████████████████████████████████| 1.3MB 55.1MB/s 
     |████████████████████████████████| 4.0MB 69.5MB/s 
     |████████████████████████████████| 471kB 67.4MB/s 
ERROR: tensorflow 2.4.1 has requ

In [ ]:
import collections

import numpy as np
import tensorflow as tf
import tensorflow_federated as tff

np.random.seed(0)

tff.federated_computation(lambda: 'Hello, World!')()

b'Hello, World!'

In [ ]:
import csv
import pandas as pd
import numpy as np

df = pd.read_csv (r'Sample Dataset.csv',index_col=False)
df = df.dropna()
df['label'] = 0
df['label'] = np.where((df['lc28'] == 1) | (df['lc56'] == 1), 1,0)
del df['lc28']
del df['lc56']
df['gender'] = np.where((df['gender'] == 'male'), 1,0)
df['age_60_and_above'] = np.where((df['age_60_and_above'] == 'Yes'), 1,0)
df_positive = df[df.label == 1]
df_negative = df[df.label ==0]
df_negative = df_negative.sample(n=(len(df_positive)))
print(len(df_positive))
print(len(df_negative))
dfs = [df_positive,df_negative]
df_balanced = pd.concat(dfs)
del df_positive
del df_negative
df_balanced = df_balanced.sample(frac=1)
df_balanced

4350
4350


cough  fever  sore_throat  ...  gender  asthma  label
71561      1      0            0  ...       0       0      1
63899      1      0            0  ...       0       0      0
54944      1      0            0  ...       0       0      1
58572      1      0            1  ...       0       0      1
30852      0      1            0  ...       1       0      1
...      ...    ...          ...  ...     ...     ...    ...
45581      0      0            0  ...       0       0      1
73040      1      0            0  ...       0       1      1
48637      1      0            0  ...       0       0      1
68550      1      0            0  ...       0       0      0
32664      0      0            0  ...       1       0      1

[8700 rows x 9 columns]

In [ ]:
msk = np.random.rand(len(df_balanced)) < 0.9

df_test = df_balanced[~msk]
df_balanced = df_balanced[msk]

print(len(df_balanced))
print(len(df_test))

7045
808


In [ ]:
x = df_test.values[:,0:8]
y = df_test.values[:,8]


x_test = tf.convert_to_tensor(x, dtype=tf.float32)
y_test  = tf.convert_to_tensor(y, dtype=tf.float32)

In [ ]:
NUM_CLIENTS = 7000
def listToList(lst):
    return [[el] for el in lst]

def fedData (df,NUM_CLIENTS):
  rowperclient = int(len(df)/NUM_CLIENTS)
  federated_dataset = []
  print(rowperclient)
  print(NUM_CLIENTS)
  #train_number = int(len(df)/100*80)
  #df_train = df_balanced[:train_number]
  #df_test = df_balanced[train_number:]
  for i in range(1,NUM_CLIENTS+1):
    start = rowperclient * (i-1)
    end = rowperclient * i
    y_train = listToList(df_balanced['label'])
    df_traindata = df_balanced.drop('label',axis=1) 
    #print(y_train[start:end])
    data_dataset = tf.data.Dataset.from_tensor_slices((df_traindata[start:end].values,y_train[start:end]))

    federated_dataset.append(data_dataset)

  print(federated_dataset)
  return federated_dataset
federated_dataset = fedData(df_balanced,NUM_CLIENTS)

1
7000
[<TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int64, tf.int32)>, <TensorSliceDataset shapes: ((8,), (1,)), types: (tf.int

## Creating Federated Environment

###Preparing Input

The following converts the preprocessed dataset into a federated dataset. This is a list, with each element in the list being a 'batchDataset', containing data relating to one client. This 'batchDataset' contains two tensors, one containing the features, and one containing the labels.

In [ ]:

BATCH_SIZE = 10000
NUM_EPOCHS = 100
SHUFFLE_BUFFER = 100

def preprocess(dataset):

  def batch_format_fn(element):
    return (tf.reshape(element[0], [-1, 8]), 
            tf.reshape(element[1], [-1, 1]))
  for element in dataset:
    element = batch_format_fn(element)
  dataset = dataset.repeat(NUM_EPOCHS).shuffle(SHUFFLE_BUFFER).batch(BATCH_SIZE)
  
  return dataset

batched_federated_dataset = [] #create empty list
for i in federated_dataset:#for every element in federated_dataset
  #print(i)
  batched_federated_dataset.append(preprocess(i))
batched_federated_dataset

[<BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,
 <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>,

In [ ]:
'''
#client_ids = np.random.choice(client_ids_total, size=NUM_CLIENTS, replace=False)
federated_train_data = [preprocess(train_dataset.create_tf_dataset_for_client(x))
  for x in client_ids
]
print(federated_train_data)
'''

NameError: ignored

In [ ]:
#dataset.create_tf_dataset_for_client(x)

NameError: ignored

### Preparing the Model

Create Keras Model,and returns that keras model as a tensorflow learning keras model

In [ ]:
batched_federated_dataset[0].cardinality

<bound method DatasetV2.cardinality of <BatchDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>>

This shis shows the batched dataset for one client. Since the batched dataset was only set to 10, there are only 10 rows

In [ ]:
for elem in batched_federated_dataset[0].take(1):
  print (elem)

(<tf.Tensor: shape=(100, 8), dtype=int64, numpy=
array([[1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0

this shows the structure of one client's data

In [ ]:
batched_federated_dataset[0].element_spec

(TensorSpec(shape=(None, 8), dtype=tf.int64, name=None),
 TensorSpec(shape=(None, 1), dtype=tf.int32, name=None))

The following are two functions which are used to create the keras model. Since it's binary classification, we use binary loss functions and metrics.

These aren't called at the moment, but are called by an initialise function later on

In [ ]:
def create_keras_model():
  return tf.keras.models.Sequential([
      tf.keras.layers.Input(shape=(8,)),
      tf.keras.layers.Dense(8,activation='relu'),
      tf.keras.layers.Dense(1,activation='sigmoid'),
  ])
def model_fn():
  keras_model = create_keras_model()
  return tff.learning.from_keras_model(
      keras_model,
      input_spec=batched_federated_dataset[0].element_spec,
      loss=tf.keras.losses.BinaryCrossentropy(from_logits=False, label_smoothing=0),
      metrics=[tf.keras.metrics.BinaryAccuracy(threshold=0.5)]
      )
print(model_fn())

### Initialize model / server

Takes the keras model from above function, and returns it's trainable variables

server_init() functions which creates a model and returns it. it's a server computation

In [ ]:
@tff.tf_computation
def server_init():
  model = model_fn()
  return model.trainable_variables

This is the initialise function, it returns a federated value (some data, where it belongs)
it returns the model, on the tff server

In [ ]:
@tff.federated_computation
def initialize_fn():
  return tff.federated_value(server_init(), tff.SERVER)

### Getting info on our Model

we obtain the model weight types from a dummy run of our model, we use these to set up our environment

In [ ]:
dummy_model = model_fn()
tf_dataset_type = tff.SequenceType(dummy_model.input_spec)

In [ ]:
str(tf_dataset_type)

'<int64[?,8],int32[?,1]>*'

In [ ]:
model_weights_type = server_init.type_signature.result

In [ ]:
str(model_weights_type)

'<float32[8,8],float32[8],float32[8,1],float32[1]>'

### Client Update

* client recieves the model's current weights
* Assigns the server's weights to the client's model
* Updates local model with local data
* applies gradient descent to weights
* Returns client weights

In [ ]:
@tf.function
def client_update(model, dataset, server_weights, client_optimizer):
  
  """Performs training (using the server model weights) on the client's dataset."""
  # Initialize the client model with the current server weights.
  client_weights = model.trainable_variables
  # Assign the server weights to the client model.
  tf.nest.map_structure(lambda x, y: x.assign(y),
                        client_weights, server_weights)
  
  # Use the client_optimizer to update the local model.
  print(dataset)
  for batch in dataset:
    print('batch: ',batch)
    with tf.GradientTape() as tape:
      # Compute a forward pass on the batch of data
      outputs = model.forward_pass(batch) #Error is here
    
    # Compute the corresponding gradient
    grads = tape.gradient(outputs.loss, client_weights)
    grads_and_vars = zip(grads, client_weights)
    
    # Apply the gradient using a client optimizer.
    client_optimizer.apply_gradients(grads_and_vars)
  return client_weights

In [ ]:
@tff.tf_computation(tf_dataset_type, model_weights_type)
def client_update_fn(tf_dataset, server_weights):
  model = model_fn()
  client_optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
  return client_update(model, tf_dataset, server_weights, client_optimizer)

<_VariantDataset shapes: ((None, 8), (None, 1)), types: (tf.int64, tf.int32)>
batch:  (<tf.Tensor 'args_1:0' shape=(None, 8) dtype=int64>, <tf.Tensor 'args_2:0' shape=(None, 1) dtype=int32>)


### Server Update

takes the mean client weights
assigns them to the model's weights

In [ ]:
@tf.function
def server_update(model, mean_client_weights):
  """Updates the server model weights as the average of the client model weights."""
  model_weights = model.trainable_variables
  # Assign the mean client weights to the server model.
  tf.nest.map_structure(lambda x, y: x.assign(y),
                        model_weights, mean_client_weights)
  return model_weights

In [ ]:
@tff.tf_computation(model_weights_type)
def server_update_fn(mean_client_weights):
  model = model_fn()
  return server_update(model, mean_client_weights)

### Assigning Federated Types

In [ ]:
federated_server_type = tff.FederatedType(model_weights_type, tff.SERVER)
federated_dataset_type = tff.FederatedType(tf_dataset_type, tff.CLIENTS)

### Next Function Definition

* Sends current weights to each client
* Client updates the weights with their data and sends the weights back
* Calculate Average of those weights
* Server updates it's weights with those averages

In [ ]:
@tff.federated_computation(federated_server_type, federated_dataset_type)
def next_fn(server_weights, federated_dataset):
  # Broadcast the server weights to the clients.
  server_weights_at_client = tff.federated_broadcast(server_weights)

  # Each client computes their updated weights.
  client_weights = tff.federated_map(
      client_update_fn, (federated_dataset, server_weights_at_client))
  
  # The server averages these updates.
  mean_client_weights = tff.federated_mean(client_weights)

  # The server updates its model.
  server_weights = tff.federated_map(server_update_fn, mean_client_weights)

  return server_weights

### Run Algorithm Function

In [ ]:
federated_algorithm = tff.templates.IterativeProcess(
    initialize_fn=initialize_fn,
    next_fn=next_fn
)


## Run Algorithm info

In [ ]:
str(federated_algorithm.initialize.type_signature)

'( -> <float32[8,8],float32[8],float32[8,1],float32[1]>@SERVER)'

In [ ]:
str(federated_algorithm.next.type_signature)

'(<server_weights=<float32[8,8],float32[8],float32[8,1],float32[1]>@SERVER,federated_dataset={<int64[?,8],int32[?,1]>*}@CLIENTS> -> <float32[8,8],float32[8],float32[8,1],float32[1]>@SERVER)'

## Evaluating the algorithm

In [ ]:
central_emnist_test = emnist_test.create_tf_dataset_from_all_clients().take(1000)
central_emnist_test = preprocess(central_emnist_test)

NameError: ignored

In [ ]:
np_batched_federated_dataset = np.asarray(batched_federated_dataset)

#x_test_tensor
#y_true = [[0, 1], [0, 0]]
#y_pred = [[0.6, 0.4], [0.4, 0.6]]

In [ ]:
def evaluate(server_state):
  keras_model = create_keras_model()
  keras_model.compile(
      loss=tf.keras.losses.BinaryCrossentropy(from_logits=False, label_smoothing=0),
      metrics=[tf.keras.metrics.BinaryAccuracy(threshold=0.5)]
  )
  keras_model.set_weights(server_state)
  keras_model.evaluate(x_test, y_test)

In [ ]:
!pip install nest_asyncio
import nest_asyncio
nest_asyncio.apply()

In [ ]:
server_state = federated_algorithm.initialize()
evaluate(server_state)

26/26 [==============================] - 0s 846us/step - loss: 0.6851 - binary_accuracy: 0.5916
